#!/usr/bin/env python3
"""Generate the ImmortalPatch test obelisk as a UV-mapped OBJ.

A stone obelisk (plinth + tapered shaft + pyramidion), ~6.2 units tall --
tombstone-plus scale next to the cemetery graves. Flat-shaded (per-face
vertices), one game material ref, and a REAL simplified-hull collision
group (plinth box + shaft frustum + pyramid: 26 triangles, not an
8-vert box) to exercise smb.py's bounding-volume-tree builder.

Usage: make_obelisk.py <out.obj>
"""
import sys

MAT = 'cherub'   # materials\cherub.mtb -- grave-statue stone, used by 7 shipped props.
# NOT cemetary/lightstone: its geometry mask (mtb +0xC) is 0x4, set-geometry only;
# props need bit 0x1 or the loader nulls materialPal and the level fails.

def ring(hw, y):
    return [(-hw, y, -hw), (hw, y, -hw), (hw, y, hw), (-hw, y, hw)]

def main(out):
    v, vt, vn, faces = [], [], [], []      # faces: (vi..., ti..., ni) quads/tris
    def emit_quad(p0, p1, p2, p3, vscale=1.0):
        """Flat quad, own verts and normal, 0..1 x 0..vscale UVs. Stored reversed
        against the caller's ring order, which is authored inward, or it renders inside-out."""
        p0, p1, p2, p3 = p0, p3, p2, p1
        base = len(v)
        e1 = [p1[i]-p0[i] for i in range(3)]
        e2 = [p3[i]-p0[i] for i in range(3)]
        n = (e1[1]*e2[2]-e1[2]*e2[1], e1[2]*e2[0]-e1[0]*e2[2], e1[0]*e2[1]-e1[1]*e2[0])
        l = max(1e-9, (n[0]**2+n[1]**2+n[2]**2) ** .5)
        vn.append(tuple(c/l for c in n))
        v.extend([p0, p1, p2, p3])
        tb = len(vt)
        vt.extend([(0, 0), (1, 0), (1, vscale), (0, vscale)])
        faces.append([(base+i, tb+i, len(vn)-1) for i in range(4)])
    def emit_tri(p0, p1, p2):
        p1, p2 = p2, p1          # same winding flip as emit_quad
        base = len(v)
        e1 = [p1[i]-p0[i] for i in range(3)]
        e2 = [p2[i]-p0[i] for i in range(3)]
        n = (e1[1]*e2[2]-e1[2]*e2[1], e1[2]*e2[0]-e1[0]*e2[2], e1[0]*e2[1]-e1[1]*e2[0])
        l = max(1e-9, (n[0]**2+n[1]**2+n[2]**2) ** .5)
        vn.append(tuple(c/l for c in n))
        v.extend([p0, p1, p2])
        tb = len(vt)
        vt.extend([(0, 0), (1, 0), (0.5, 1)])
        faces.append([(base+i, tb+i, len(vn)-1) for i in range(3)])

    def side_quads(bot, top, vscale):
        for i in range(4):
            j = (i + 1) % 4
            emit_quad(bot[i], bot[j], top[j], top[i], vscale)

    # plinth 1.2x1.2 x 0.5 (slimmed from 1.6: hitbox felt fat in-game), shaft
    # taper 1.2->0.8 over 4.5, pyramidion to 6.2
    pb, pt = ring(0.6, 0.0), ring(0.6, 0.5)
    sb, st = ring(0.6, 0.5), ring(0.4, 5.0)
    apex = (0.0, 6.2, 0.0)
    side_quads(pb, pt, 0.3)                       # plinth sides
    emit_quad(pt[3], pt[2], pt[1], pt[0], 1.0)    # plinth top (up)
    side_quads(sb, st, 2.8)                       # shaft sides
    for i in range(4):                            # pyramidion
        j = (i + 1) % 4
        emit_tri(st[i], st[j], apex)

    visual_end_v, visual_end_t, visual_end_n = len(v), len(vt), len(vn)

    # collision hull: same shape, shared verts, no uv/normals
    cv = ring(0.6, 0.0) + ring(0.6, 0.5) + ring(0.6, 0.5) + ring(0.4, 5.0) + [apex]
    cb = len(v); v.extend(cv)
    def q(a, b, c, d): return [(a, c, b), (c, a, d)]   # winding flip, see emit_quad
    ct = []
    for lo, hi in ((0, 4), (8, 12)):              # plinth sides, shaft sides
        for i in range(4):
            j = (i + 1) % 4
            ct += q(lo+i, lo+j, hi+j, hi+i)
    ct += q(3, 2, 1, 0)                           # plinth bottom
    ct += q(4, 5, 6, 7)                           # plinth top
    for i in range(4):                            # pyramid sides
        j = (i + 1) % 4
        ct.append((12+i, 16, 12+j))               # winding flip, see emit_quad

    with open(out, 'w') as f:
        f.write('# ImmortalPatch test obelisk (generated by make_obelisk.py)\n')
        for p in v: f.write('v %r %r %r\n' % p)
        for t in vt: f.write('vt %r %r\n' % t)
        for n in vn: f.write('vn %r %r %r\n' % n)
        f.write('g Intact\nusemtl %s\n' % MAT)
        for face in faces:
            f.write('f ' + ' '.join('%d/%d/%d' % (vi+1, ti+1, ni+1) for vi, ti, ni in face) + '\n')
        f.write('g Intact.Collision_Mesh01\n')
        for a, b, c in ct:
            f.write('f %d %d %d\n' % (cb+a+1, cb+b+1, cb+c+1))
    print('wrote %s: %d visual verts / %d faces, collision %d verts / %d tris'
          % (out, visual_end_v, len(faces), len(cv), len(ct)))

if __name__ == '__main__':
    main(sys.argv[1])
